#1
import random
import string

def random_user_id():
    characters = string.ascii_letters + string.digits   #The ascii_letters constant in the string
    #module contains all the English letters from a to z.
    #These letters are in lowercase and uppercase as a single string.
    user_id = ''.join(random.choice(characters) for _ in range(6)) #random.choice(characters):
#This function call selects a single random character from the characters sequence.
#''.join(...):
#This method concatenates the characters generated by the generator expression into a single string. The empty string '' before
#.join() signifies that the characters should be joined without any separator between them.
    return user_id
print(random_user_id())

#2
def user_id_gen_by_user():
    length = int(input("Enter the number of characters per ID: "))
    count = int(input("Enter the number of IDs to generate: "))
    
    chars = string.ascii_letters + string.digits 
    ids = [''.join(random.choice(chars) for _ in range(length)) for _ in range(count)]
    
    return ids
#3
def rgb_color_gen():
    r = random.randint(0, 255) #tao so nguyen random tu 0 toi 255
    g = random.randint(0, 255)
    b = random.randint(0, 255)
    return f"rgb({r},{g},{b})"

#4
def list_of_hexa_colors(n=1):
    return ['#' + ''.join(random.choice('0123456789ABCDEF') for _ in range(6)) for _ in range(n)]

#5
def list_of_rgb_colors(n=1):
    return [rgb_color_gen() for _ in range(n)]

#6
def generate_colors(color_type, n=1):
    if color_type.lower() == 'hexa':
        return list_of_hexa_colors(n)
    elif color_type.lower() == 'rgb':
        return list_of_rgb_colors(n)
    else:
        return "Error: choose 'hexa' or 'rgb'"

#7
def shuffle_list(lst):
    random.shuffle(lst) #shuffle
    return lst

#8
def random_unique_numbers():
    return random.sample(range(10), 7) #lay ngau nhien so trong day